# Generated by Django 3.2.5 on 2021-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_blogdb_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='docid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
